<a href="https://colab.research.google.com/github/pietrolima01/TCCTerrorismo/blob/main/ETL_TerrorismoGlobal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importar as bibliotecas para tratar os dados
import pandas as pd
import seaborn as srn
import statistics as sts

In [ ]:
#Importar os dados para realizar os tratamentos
#A Base de Dados sempre será disponibilizada e atualizada no mesmo diretório
dsFato = pd.read_csv("fato.csv", sep=";")
dsFato.head()

C:\Users\Pietro Tayrone\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID do evento,Ano do evento,Mês do evento,Dia do Evento,Estendido,Data da resolução,ID_Pais,ID_Regiao,Estado,Cidade,...,nwoundus,nwoundte,Ataque a Propriedade,Extensão da propriedade,ID_DescricaoPropriedade,Descrição da propriedade,Valor da propriedade,Comentário sobre a propriedade,Houve refém?,hostkidoutcome_txt
0,"2,00001E+11",2000,1,1,0,NaN,139,11,Kavango,Muitjiku,...,0.0,NaN,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,"2,00001E+11",2000,1,1,1,NaN,139,11,Kavango,Muitjiku,...,0.0,NaN,-9.0,NaN,NaN,NaN,NaN,NaN,1.0,Unknown
2,"2,00001E+11",2000,1,1,0,NaN,92,6,Jammu and Kashmir,Udhampur,...,0.0,NaN,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,"2,00001E+11",2000,1,1,0,NaN,1003,9,Kosovo (Province),Peje,...,0.0,0.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,"2,00001E+11",2000,1,1,0,NaN,182,11,Banaadir,Mogadishu,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [ ]:
# Existem algumas colunas que não serão utilizadas no dashboard, por isso serão removidas
dsFato = dsFato.drop(columns=['nkillus','nwoundus','nwoundte'])
dsFato.head()

,ID do evento,Ano do evento,Mês do evento,Dia do Evento,Estendido,Data da resolução,ID_Pais,ID_Regiao,Estado,Cidade,...,nkillter,nwound,Ataque a Propriedade,Extensão da propriedade,ID_DescricaoPropriedade,Descrição da propriedade,Valor da propriedade,Comentário sobre a propriedade,Houve refém?,hostkidoutcome_txt
0,"2,00001E+11",2000,1,1,0,NaN,139,11,Kavango,Muitjiku,...,0.0,7.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,"2,00001E+11",2000,1,1,1,NaN,139,11,Kavango,Muitjiku,...,0.0,7.0,-9.0,NaN,NaN,NaN,NaN,NaN,1.0,Unknown
2,"2,00001E+11",2000,1,1,0,NaN,92,6,Jammu and Kashmir,Udhampur,...,NaN,2.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,"2,00001E+11",2000,1,1,0,NaN,1003,9,Kosovo (Province),Peje,...,0.0,1.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,"2,00001E+11",2000,1,1,0,NaN,182,11,Banaadir,Mogadishu,...,0.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [ ]:
#Agora alguns cabeçalhos que estão em inglês, serão traduzidos
dsFato.rename(columns={'suicide': 'Ataque suicida?'}, inplace = True)
dsFato.rename(columns={'corp1': 'Alvo'}, inplace = True)
dsFato.rename(columns={'nkillter': 'Terroristas mortos'}, inplace = True)
dsFato.rename(columns={'nwound': 'Número de feridos'}, inplace = True)
dsFato.rename(columns={'hostkidoutcome_txt': 'Resumo do resgate'}, inplace = True)
dsFato.head()

,ID do evento,Ano do evento,Mês do evento,Dia do Evento,Estendido,Data da resolução,ID_Pais,ID_Regiao,Estado,Cidade,...,Terroristas mortos,Número de feridos,Ataque a Propriedade,Extensão da propriedade,ID_DescricaoPropriedade,Descrição da propriedade,Valor da propriedade,Comentário sobre a propriedade,Houve refém?,Resumo do resgate
0,"2,00001E+11",2000,1,1,0,NaN,139,11,Kavango,Muitjiku,...,0.0,7.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,"2,00001E+11",2000,1,1,1,NaN,139,11,Kavango,Muitjiku,...,0.0,7.0,-9.0,NaN,NaN,NaN,NaN,NaN,1.0,Unknown
2,"2,00001E+11",2000,1,1,0,NaN,92,6,Jammu and Kashmir,Udhampur,...,NaN,2.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,"2,00001E+11",2000,1,1,0,NaN,1003,9,Kosovo (Province),Peje,...,0.0,1.0,-9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,"2,00001E+11",2000,1,1,0,NaN,182,11,Banaadir,Mogadishu,...,0.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [ ]:
#Agora será identificado os dados nulos
dsFato.isna().mean().round(4)

ID do evento                      0.0000
Ano do evento                     0.0000
Mês do evento                     0.0000
Dia do Evento                     0.0000
Estendido                         0.0000
Data da resolução                 0.9926
ID_Pais                           0.0000
ID_Regiao                         0.0000
Estado                            0.0001
Cidade                            0.0039
latitude                          0.0075
longitude                         0.0075
Localidade                        0.5163
Resumo do Ocorrido                0.0019
ID_TipoCrime                      0.8942
multiple                          0.2680
success                           0.2680
Ataque suicida?                   0.2680
ID_TipoAtaque                     0.2680
ID_TipoAlvo                       0.2680
ID_SubTipoAlvo                    0.3180
Alvo                              0.3569
Alvo principal                    0.2697
ID_GrupoTerror                    0.0000
Grupo Terrorista                  0.2687
SubNome do Grupo Terrorista       0.9808
Motivação                         0.6433
ID_TipoArma                       0.3118
ID_SubTipoArma                    0.3505
Detalhe da Arma                   0.6441
Número de mortos                  0.3282
Terroristas mortos                0.3265
Número de feridos                 0.3468
Ataque a Propriedade              0.3123
Extensão da propriedade           0.7187
ID_DescricaoPropriedade           0.7187
Descrição da propriedade          0.7187
Valor da propriedade              0.8575
Comentário sobre a propriedade    0.6735
Houve refém?                      0.3125
Resumo do resgate                 0.9559
dtype: float64

In [ ]:
#Preencher os valores nulos com 'Unknown' para manter um padrão
dsFato.update(dsFato.fillna('Unknown'))
dsFato.isna().mean().round(4)

ID do evento                      0.0
Ano do evento                     0.0
Mês do evento                     0.0
Dia do Evento                     0.0
Estendido                         0.0
Data da resolução                 0.0
ID_Pais                           0.0
ID_Regiao                         0.0
Estado                            0.0
Cidade                            0.0
latitude                          0.0
longitude                         0.0
Localidade                        0.0
Resumo do Ocorrido                0.0
ID_TipoCrime                      0.0
multiple                          0.0
success                           0.0
Ataque suicida?                   0.0
ID_TipoAtaque                     0.0
ID_TipoAlvo                       0.0
ID_SubTipoAlvo                    0.0
Alvo                              0.0
Alvo principal                    0.0
ID_GrupoTerror                    0.0
Grupo Terrorista                  0.0
SubNome do Grupo Terrorista       0.0
Motivação                         0.0
ID_TipoArma                       0.0
ID_SubTipoArma                    0.0
Detalhe da Arma                   0.0
Número de mortos                  0.0
Terroristas mortos                0.0
Número de feridos                 0.0
Ataque a Propriedade              0.0
Extensão da propriedade           0.0
ID_DescricaoPropriedade           0.0
Descrição da propriedade          0.0
Valor da propriedade              0.0
Comentário sobre a propriedade    0.0
Houve refém?                      0.0
Resumo do resgate                 0.0
dtype: float64

In [ ]:
#A partir deste ponto será realizada uma análise exploratória dos dados para que seja identificado os possíveis pontos que deverão ser tratados

In [ ]:
#tamanho da base
dsFato.shape

(111854, 41)

In [ ]:
agroup = dsFato.groupby(['Ataque suicida?']).size()
agroup

Ataque suicida?
0.0        77061
1.0         4819
Unknown    29974
dtype: int64

In [ ]:
a = {'Unknown':'não', 0:'não', 1:'sim'}
dsFato['Ataque suicida?'] = dsFato['Ataque suicida?'].map(a)

In [ ]:
Agrupado = dsFato.groupby(['Ataque a Propriedade']).size()
Agrupado

Ataque a Propriedade
-9.0       15687
0.0        32636
1.0        28601
Unknown    34930
dtype: int64

In [ ]:
a = {'Unknown':'não', 0:'não', 1:'sim','-9':'não'}
dsFato['Ataque a Propriedade'] = dsFato['Ataque a Propriedade'].map(a)

In [ ]:
#As colunas ID devem ser número inteiros, por isso o que for diferente de um número intero será substituído por zero
dsFato['ID_DescricaoPropriedade'] = dsFato['ID_DescricaoPropriedade'].replace('Unknown','0')
dsFato['ID_GrupoTerror'] = dsFato['ID_GrupoTerror'].replace('Unknown','0')
dsFato['ID_TipoCrime'] = dsFato['ID_TipoCrime'].replace('Unknown','0')
dsFato['ID_Pais'] = dsFato['ID_Pais'].replace('Unknown','0')
dsFato['ID_Regiao'] = dsFato['ID_Regiao'].replace('Unknown','0')
dsFato['ID_TipoAtaque'] = dsFato['ID_TipoAtaque'].replace('Unknown','0')
dsFato['ID_TipoAlvo'] = dsFato['ID_TipoAlvo'].replace('Unknown','0')
dsFato['ID_SubTipoAlvo'] = dsFato['ID_SubTipoAlvo'].replace('Unknown','0')
dsFato['ID_TipoArma'] = dsFato['ID_TipoArma'].replace('Unknown','0')
dsFato['ID_SubTipoArma'] = dsFato['ID_SubTipoArma'].replace('Unknown','0')

dsFato['ID_DescricaoPropriedade'] = dsFato['ID_DescricaoPropriedade'].replace('#N/D','0')
dsFato['ID_GrupoTerror'] = dsFato['ID_GrupoTerror'].replace('#N/D','0')
dsFato['ID_TipoCrime'] = dsFato['ID_TipoCrime'].replace('#N/D','0')
dsFato['ID_Pais'] = dsFato['ID_Pais'].replace('#N/D','0')
dsFato['ID_Regiao'] = dsFato['ID_Regiao'].replace('#N/D','0')
dsFato['ID_TipoAtaque'] = dsFato['ID_TipoAtaque'].replace('#N/D','0')
dsFato['ID_TipoAlvo'] = dsFato['ID_TipoAlvo'].replace('#N/D','0')
dsFato['ID_SubTipoAlvo'] = dsFato['ID_SubTipoAlvo'].replace('#N/D','0')
dsFato['ID_TipoArma'] = dsFato['ID_TipoArma'].replace('#N/D','0')
dsFato['ID_SubTipoArma'] = dsFato['ID_SubTipoArma'].replace('#N/D','0')

dsFato['ID_DescricaoPropriedade']=dsFato['ID_DescricaoPropriedade'].astype(int)
dsFato['ID_GrupoTerror']=dsFato['ID_GrupoTerror'].astype(int)
dsFato['ID_TipoCrime']=dsFato['ID_TipoCrime'].astype(int)
dsFato['ID_Pais']=dsFato['ID_Pais'].astype(int)
dsFato['ID_Regiao']=dsFato['ID_Regiao'].astype(int)
dsFato['ID_TipoAtaque']=dsFato['ID_TipoAtaque'].astype(int)
dsFato['ID_TipoAlvo']=dsFato['ID_TipoAlvo'].astype(int)
dsFato['ID_SubTipoAlvo']=dsFato['ID_SubTipoAlvo'].astype(int)
dsFato['ID_TipoArma']=dsFato['ID_TipoArma'].astype(int)
dsFato['ID_SubTipoArma']=dsFato['ID_SubTipoArma'].astype(int)

In [ ]:
Agrupado = dsFato.groupby(['Houve refém?']).size()
Agrupado

Houve refém?
-9.0         154
0.0        71791
1.0         4951
Unknown    34958
dtype: int64

In [ ]:
a = {'Unknown':'não', 0:'não', 1:'sim','-9':'não'}
dsFato['Houve refém?'] = dsFato['Houve refém?'].map(a)

In [ ]:
#Agora as informações das dimensões serão inseridas na fato de acordo com os respectivos ID's

,ID do evento,Data,Ano do evento,Mês do evento,Dia do Evento,Estendido,Data da resolução,ID_Pais,ID_Regiao,Estado,...,Número de feridos,Ataque a Propriedade,Extensão da propriedade,ID_DescricaoPropriedade,Descrição da propriedade,Valor da propriedade,Comentário sobre a propriedade,Houve refém?,Resumo do resgate,Descrição do crime
0,"2,00001E+11",,2000,1,1,0,Unknown,92,6,Jammu and Kashmir,...,2,NaN,Unknown,0,Unknown,Unknown,Unknown,não,Unknown,Insurgency/Guerilla Action
1,"2,00001E+11",,2000,1,1,0,Unknown,186,6,Norhtern,...,Unknown,não,Unknown,0,Unknown,Unknown,Unknown,não,Unknown,Insurgency/Guerilla Action
2,"2,00001E+11",,2000,1,3,0,Unknown,228,10,Adan,...,0,não,Unknown,0,Unknown,Unknown,Unknown,não,Unknown,Insurgency/Guerilla Action
3,"2,00001E+11",,2000,1,6,0,Unknown,167,9,Chechnya (Republic),...,0,sim,4,4,Unknown,Unknown,The surgery and intensive care departments wer...,não,Unknown,Insurgency/Guerilla Action
4,"2,00001E+11",,2000,1,24,0,Unknown,92,6,Jammu and Kashmir,...,6,NaN,Unknown,0,Unknown,Unknown,Unknown,não,Unknown,Insurgency/Guerilla Action

In [ ]:
df3= pd.read_csv('dimensaoRegiao.csv', sep=";")
dw = pd.merge(dsFato, df3, on = 'ID_Regiao', how = 'inner')

In [ ]:
df4= pd.read_csv('dimensaoSubTipoDeAlvo.csv', sep=";")
dw1 = pd.merge(dw, df4, on = 'ID_SubTipoAlvo', how = 'inner')

In [ ]:
df5= pd.read_csv('dimensaoSubTipoDeArma.csv', sep=";")
dw2 = pd.merge(dw1, df5, on = 'ID_SubTipoArma', how = 'inner')

In [ ]:
df6= pd.read_csv('dimensaoTipoDeAlvo.csv', sep=";")
dw3 = pd.merge(dw2, df6, on = 'ID_TipoAlvo', how = 'inner')

In [ ]:
df7= pd.read_csv('dimensaoTipoDeArma.csv', sep=";")
dw4 = pd.merge(dw3, df7, on = 'ID_TipoArma', how = 'inner')

In [ ]:
df8= pd.read_csv('dimensaoTipoDeAtaque.csv', sep=";")
dw5 = pd.merge(dw4, df8, on = 'ID_TipoAtaque', how = 'inner')

In [ ]:
df9= pd.read_csv('dimensaoTipoDeCrime.csv', sep=";")
dw6 = pd.merge(dw5, df9, on = 'ID_TipoCrime', how = 'inner')

In [ ]:
dw6.head()

,ID do evento,Data,Ano do evento,Mês do evento,Dia do Evento,Estendido,Data da resolução,ID_Pais,ID_Regiao,Estado,...,Comentário sobre a propriedade,Houve refém?,Resumo do resgate,Nome da região,Descrição do SubTipo do Alvo,Descrição do SubTipo da Arma,Descrição do Tipo do Alvo,Descrição da arma,Descrição do Ataque,Descrição do crime
0,"2,01611E+11",,2016,11,5,0,Unknown,1004,11,Jubek,...,Unknown,não,Unknown,Sub-Saharan Africa,Restaurant/Bar/Café,Unknown Gun Type,Business,Firearms,Armed Assault,Other Crime Type
1,"2,00304E+11",,2003,4,18,0,Unknown,6,10,Jijel (Province),...,Unknown,não,Unknown,Middle East & North Africa,Restaurant/Bar/Café,Unknown Gun Type,Business,Firearms,Armed Assault,Other Crime Type
2,"2,00402E+11",,2004,2,10,0,Unknown,6,10,Jijel,...,Unknown,não,Unknown,Middle East & North Africa,Restaurant/Bar/Café,Unknown Gun Type,Business,Firearms,Armed Assault,Other Crime Type
3,"2,01111E+11",,2011,11,25,0,Unknown,95,10,Diyala,...,Unknown,não,Unknown,Middle East & North Africa,Restaurant/Bar/Café,Unknown Gun Type,Business,Firearms,Armed Assault,Other Crime Type
4,"2,01602E+11",,2016,2,8,0,Unknown,209,10,Istanbul,...,It is unknown if any property was damaged in t...,não,Unknown,Middle East & North Africa,Restaurant/Bar/Café,Unknown Gun Type,Business,Firearms,Armed Assault,Other Crime Type

In [ ]:
#Exportar para a pasta onde o Power BI fará a importação dos dados no formato csv
dw6.to_csv (r'C:\Users\Pietro Tayrone\Desktop\Base Py\baseTerrorismoTratada.csv', index = None, header=True)

In [ ]:
#Fim